/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.akman.poker.view;

import com.akman.poker.utils.Membership;
import java.awt.event.KeyEvent;

/**
 *
 * @author AKL SOFT
 */
public class frmAddMembershipType extends javax.swing.JDialog {

    /**
     * Creates new form frmAddMembershipType
     *
     * @param parent
     * @param modal
     */
    frmInvoice inv = new frmInvoice();

    public frmAddMembershipType(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        if (parent.getTitle().equals("Time Managment")) {
            this.inv = (frmInvoice) parent;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnOneDayMembership = new javax.swing.JButton();
        btnOneMonthMembership = new javax.swing.JButton();
        btnOneYearMembership = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 20);
        flowLayout1.setAlignOnBaseline(true);
        jPanel1.setLayout(flowLayout1);

        btnOneDayMembership.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/akman/poker/images/Membership 1 day.png"))); // NOI18N
        btnOneDayMembership.setPreferredSize(new java.awt.Dimension(300, 150));
        btnOneDayMembership.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneDayMembershipActionPerformed(evt);
            }
        });
        jPanel1.add(btnOneDayMembership);

        btnOneMonthMembership.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/akman/poker/images/Membership - Month.png"))); // NOI18N
        btnOneMonthMembership.setPreferredSize(new java.awt.Dimension(300, 150));
        btnOneMonthMembership.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneMonthMembershipActionPerformed(evt);
            }
        });
        jPanel1.add(btnOneMonthMembership);

        btnOneYearMembership.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/akman/poker/images/Membership - Year.png"))); // NOI18N
        btnOneYearMembership.setPreferredSize(new java.awt.Dimension(300, 150));
        btnOneYearMembership.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneYearMembershipActionPerformed(evt);
            }
        });
        jPanel1.add(btnOneYearMembership);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOneDayMembershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneDayMembershipActionPerformed
        frmCustomer cus = new frmCustomer(Membership.Day, inv);
        dispose();
        cus.setVisible(true);

    }//GEN-LAST:event_btnOneDayMembershipActionPerformed

    private void btnOneMonthMembershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneMonthMembershipActionPerformed
        frmCustomer cust = new frmCustomer(Membership.Month, inv);
        dispose();
        cust.setVisible(true);
    }//GEN-LAST:event_btnOneMonthMembershipActionPerformed

    private void btnOneYearMembershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneYearMembershipActionPerformed
        frmCustomer customer = new frmCustomer(Membership.Year, inv);
        dispose();
        customer.setVisible(true);

    }//GEN-LAST:event_btnOneYearMembershipActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased

        if (evt.getKeyChar() == KeyEvent.VK_CANCEL) {
            dispose();
        }
    }//GEN-LAST:event_formKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAddMembershipType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAddMembershipType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAddMembershipType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAddMembershipType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmAddMembershipType dialog = new frmAddMembershipType(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOneDayMembership;
    private javax.swing.JButton btnOneMonthMembership;
    private javax.swing.JButton btnOneYearMembership;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
